spring:
  cloud:
    stream:
      bindings:
        output:
          destination: test_topic
        partitionKey:
          producer:
            partition-key-expression: headers['messageKey']
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8181
